name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  testsuite:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Lint v2 and v3
        run: |
            node_modules/.bin/webpack --mode=production && mv dist/manifest-v2.json dist/manifest.json && rm dist/manifest-v3.json
            yarn lint
            node_modules/.bin/webpack --mode=production && mv dist/manifest-v3.json dist/manifest.json && rm dist/manifest-v2.json
            yarn lint

      - name: Build v2 and v3 manifest addon
        run: |
            yarn build:v2
            yarn build:v3
