name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  testsuite:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Lint v2 and v3
        run: |
          node_modules/.bin/webpack --mode=production && mv dist/manifest-v2.json dist/manifest.json && rm dist/manifest-v3.json
          yarn lint

        # Do not validate v3 ... well not working atm, requires some more work. Doh!
        # node_modules/.bin/webpack --mode=production && mv dist/manifest-v3.json dist/manifest.json && rm dist/manifest-v2.json
        # yarn lint
      - name: Build v2 and v3 manifest addon
        run: |
          yarn build:v2
          yarn build:v3
          mv web-ext-artifacts/typo3_tdk_gitpod-v2.zip typo3_tdk_gitpod-manifest-v2-${{ github.event.release.tag_name }}.zip
          mv web-ext-artifacts/typo3_tdk_gitpod-v3.zip typo3_tdk_gitpod-manifest-v3-${{ github.event.release.tag_name }}.zip
          ls -la

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            typo3_tdk_gitpod-manifest-v2-${{ github.event.release.tag_name }}.zip
            typo3_tdk_gitpod-manifest-v3-${{ github.event.release.tag_name }}.zip

  darwin:
    name: Build for Safari
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Build v3 manifest addon
        run: |
          yarn build:v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 13.4

      - name: Build Safari
        run: |
          yarn build:safari
          mv "TYPO3 TDK GitPod Integration/DerivedData/Build/Products/Debug/TYPO3 TDK GitPod Integration.app" "TYPO3 TDK GitPod Integration.app"
          zip -r TYPO3-TDK-GitPod-${{ github.event.release.tag_name }}.zip "TYPO3 TDK GitPod Integration.app"
          ls -la
      - name: Upload safari release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            TYPO3-TDK-GitPod-Safari-${{ github.event.release.tag_name }}.zip
