name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  prepare:
    name: Checkout and install packages
    runs-on: ubuntu-20.04
    outputs:
      ref: ${{ steps.clean_ref.outputs.value }}
    steps:
      - name: Run find-and-replace to remove slashes
        uses: mad9000/actions-find-and-replace-string@1
        id: clean_ref
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Lint v2 and v3
        run: |
          node_modules/.bin/webpack --mode=production && mv dist/manifest-v2.json dist/manifest.json
          yarn lint

  webextension:
    name: Build Web Extension (Chrome, Firefox, Edge)
    needs: [
      prepare
    ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Build v2 and v3 manifest addon
        run: |
          yarn build:v2
          yarn build:v3
          ls -la
          ls -la web-ext-artifacts/
          mv web-ext-artifacts/typo3-tdk-gitpod-v2.zip "TYPO3-TDK-GitPod-Manifest-v2-${{needs.prepare.outputs.ref}}.zip"
          mv web-ext-artifacts/typo3-tdk-gitpod-v3.zip "TYPO3-TDK-GitPod-Manifest-v3-${{needs.prepare.outputs.ref}}.zip"
          ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: webextension
          path: TYPO3-TDK-GitPod-*

  darwin:
    name: Build for Safari
    runs-on: macos-12
    needs: [
      prepare
    ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install packages
        run: yarn install

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 13.4

      - name: Build Safari
        run: |
          yarn build:safari
          node_modules/.bin/appdmg package-dmg.json TYPO3-TDK-GitPod-${{needs.prepare.outputs.ref}}.dmg
          ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: extension-safari
          path: TYPO3-TDK-GitPod-*

  upload:
    name: Upload release files
    runs-on: ubuntu-20.04
    needs: [
      webextension,
      darwin
    ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: webextension

    - uses: actions/download-artifact@v3
      with:
        name: extension-safari

    - name: Build Safari
      run: |
        ls -la

    - name: Upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          TYPO3-TDK-GitPod-*
